feat: Add NaturalLangService and change type of authentication
vamelchenia/translate-api-bridge pull request #5
Opened 2023-11-23 14:12 UTC by evgenysavonkin

1. Add NaturalLangService and its implementation for one word 
3. Change type of authentication using properties file "sensitive.properties" which stores user credentials

2023-11-24 21:54 UTC, vamelchenia approved these changes

2023-11-25 19:42 UTC, Electron3D requested changes

2023-11-25 19:42 UTC, Electron3D commented on pom.xml
data jpa and h2 aren't needed or do you use it somewhere?

2023-11-25 19:42 UTC, Electron3D commented on src/main/java/com/nerdtranslator/lingueeapibridge/service/NaturalLangService.java
I think would be better to specify that we use API in the service naming. TextToSpeechApiServiceImpl would be better too on my mind. Or we should rename translationApiService to keep one design code.

2023-11-25 19:42 UTC, Electron3D commented on src/main/java/com/nerdtranslator/lingueeapibridge/service/impl/NerdTranslatorServiceImpl.java
unnecessary changes, this will lead to additional conflicts

2023-11-25 19:42 UTC, Electron3D commented on src/main/java/com/nerdtranslator/lingueeapibridge/service/impl/TextToSpeechServiceImpl.java
> +        final String finalCredentialsString = credentialsString;
need changes with credentials strings, same as in NaturalLanguageService, final string isn't needed

2023-11-25 19:42 UTC, Electron3D commented on src/main/java/com/nerdtranslator/lingueeapibridge/service/impl/NaturalLangServiceImpl.java
> +        final String finalCredentialsString = credentialsString;
need changes with credentials strings, final string isn't needed

2023-11-25 19:42 UTC, Electron3D commented on src/main/resources/application.properties
add variables from sensitive.properties file as link down below using ${} syntax

2023-11-25 19:42 UTC, Electron3D commented on src/main/java/com/nerdtranslator/lingueeapibridge/service/impl/TextToSpeechServiceImpl.java
> +        try (FileInputStream inputStream = new FileInputStream("src/main/resources/sensitive.properties")) {
Don't read credentials straight from sensitive.properties, add variables as link in application.properties, inject them using Value annotation

2023-11-25 19:42 UTC, Electron3D commented on src/main/java/com/nerdtranslator/lingueeapibridge/service/impl/NaturalLangServiceImpl.java
> +        try (FileInputStream inputStream = new FileInputStream("src/main/resources/sensitive.properties")) {
Don't read credentials straight from sensitive.properties, add variables as link in application.properties, inject them using Value annotation

2023-11-26 13:27 UTC, Electron3D approved these changes

2023-11-26 13:29 UTC, merged